- name: setup mysql server
  hosts: dbsrv
  become: true
  vars:
    dbname: sayeed
    dbuser: playuser
    dbpass: admin123
  tasks:
    - name: installing mysql server
      yum:
        name: mariadb-server
        state: present

    - name: installing python mysql server
      yum:
        name: MySQL-python
        state: present

    - name: starting the mysql service
      service:
        name: mariadb
        state: started

    - name: creating the mysql database accounts
      mysql_db:
        name: "{{dbname}}"
        state: present
      register: db_out

    - debug:
        var: db_out

    - name: creating the mysql user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '".*":ALL,GRANT'
        state: present
      register: sqluser_out

    - debug:
        var: sqluser_out.user

